// <auto-generated />
using BidConReport.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BidConReport.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230227195437_TagsAndImportSettings")]
    partial class TagsAndImportSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BidConReport.Shared.Models.EstimationImportSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostBeforeChangesAccount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CostFactorAccount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HiddenTag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NetCostAccount")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SettingsName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstimationImportSettings");
                });

            modelBuilder.Entity("BidConReport.Shared.Models.QuickTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("QuickTag");
                });

            modelBuilder.Entity("BidConReport.Shared.Models.SelectionTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("SelectionTag");
                });

            modelBuilder.Entity("EstimationImportSettingsQuickTag", b =>
                {
                    b.Property<int>("EstimationImportSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("QuickTagsId")
                        .HasColumnType("int");

                    b.HasKey("EstimationImportSettingsId", "QuickTagsId");

                    b.HasIndex("QuickTagsId");

                    b.ToTable("SettingQuickTags", (string)null);
                });

            modelBuilder.Entity("EstimationImportSettingsSelectionTag", b =>
                {
                    b.Property<int>("EstimationImportSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("SelectionTagsId")
                        .HasColumnType("int");

                    b.HasKey("EstimationImportSettingsId", "SelectionTagsId");

                    b.HasIndex("SelectionTagsId");

                    b.ToTable("SettingSelectionTags", (string)null);
                });

            modelBuilder.Entity("EstimationImportSettingsQuickTag", b =>
                {
                    b.HasOne("BidConReport.Shared.Models.EstimationImportSettings", null)
                        .WithMany()
                        .HasForeignKey("EstimationImportSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidConReport.Shared.Models.QuickTag", null)
                        .WithMany()
                        .HasForeignKey("QuickTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EstimationImportSettingsSelectionTag", b =>
                {
                    b.HasOne("BidConReport.Shared.Models.EstimationImportSettings", null)
                        .WithMany()
                        .HasForeignKey("EstimationImportSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BidConReport.Shared.Models.SelectionTag", null)
                        .WithMany()
                        .HasForeignKey("SelectionTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
